#! /bin/zsh
if [[ $ZSH_EVAL_CONTEXT == 'toplevel' ]]
then
    echo "Usage:\n  source install"
    exit 1
fi

cp --backup=t --suffix=.pre_yabs .zshrc $HOME
cp -R .yabs $HOME
source $HOME/.zshrc

request_install() {
    if [[ "$#" -lt 2 ]]
    then
        echo "$ERROR request_install takes at least two parameters"
        exit 1
    fi

    CONFIRMATION=true

    if [[ -f "$2" ]]
    then
        request_confirmation "Do you want to overwrite $(basename $1) ?"
        CONFIRMATION=$?
    fi
    if [[ $CONFIRMATION -eq 0 ]]
    then
        echo "$OK Copying $1 to $2"
        cp $1 $2
    else
        echo "$INDETERMINATE $2 will not be overriden"
    fi

}

request_install .gitconfig ~/.gitconfig
request_install .vimrc ~/.vimrc
request_install powerline/default.json ~/.config/powerline/themes/vim/default.json
