#!/bin/zsh
#  =============
#  == kubectl ==
#  =============
#
#  Contains some utilities allowing to ease complex kubectl tasks
#
#  envs:
#
#  functions:
#   - kubens:
#     Switches kubectl namespaces,
#
#  aliases:

kubens () {
    if [[ "$#" -eq 0 ]]
    then
        echo ${$(kubectl config view --minify | grep namespace | tr ":" " ")[2]}
        return 0
    fi

    kubectl config set-context --current --namespace=$1
    kubens
}
